### ISSUE TITLE
can't seem to open `tutorial/tutorial.ipynb`

### ISSUE THREAD

**Issue by bhuang3** [facebookresearch/torcharrow#123]
<img width="1247" alt="Screen Shot 2021-12-22 at 10 01 09 AM" src="https://user-images.githubusercontent.com/2781272/147112479-e6838b55-0f26-4b91-8620-8c27445583fa.png">

**Comment by vancexu** [comment]
I've google a bit and this seems Github issues on rendering ipynb files. It may need help from Github to address this. 
A common work around is using https://nbviewer.org/github/facebookresearch/torcharrow/blob/main/tutorial/tutorial.ipynb instead, which will load the ipynb from main and render successfully.

**Comment by wenleix** [comment]
Looks like GitHub fixed the issue now (at least it rendered on myside: https://github.com/facebookresearch/torcharrow/blob/main/tutorial/tutorial.ipynb)

**Comment by wenleix** [comment]
Closed since it's now rendered normally.
