### ISSUE TITLE
Remove experimental batching/unbatching API

### ISSUE THREAD

**Issue by wenleix** [facebookresearch/torcharrow#29]
https://github.com/facebookresearch/torcharrow/blob/64014481d942229ca5d9222fe4532a29b2628da3/torcharrow/icolumn.py#L1727-L1744

This is an experimental prototype API. However since customized batching in deep learning can be quite adhoc (e.g. https://github.com/pytorch/data/blob/cbd19f01fe92b7039583ea9fff29df2c6a898a9c/torchdata/datapipes/iter/transform/bucketbatcher.py#L28-L34), it's beyond DataFrame API's scope to handle it and should be handled by DataLoader instead.

**Comment by dongreenberg** [comment]
Ehhhh I'm not so sure. The standard batching case really is this simple. I would consider this a convenience for when the user wants to quickly form some batches to start iterating to test a model or something - they won't be using the dataloader then.

**Comment by dongreenberg** [comment]
Ya that sounds fine to me. I'm not super opinionated either way, just advocating the "syntactic sugar is nice" side to balance to "pruning the API" side 😀.

**Comment by wenleix** [comment]
Add docstring with `EXPERIMENTAL API` for now: 

https://github.com/facebookresearch/torcharrow/blob/380e1cbaf334b49d52242596c79627d456ef3b0d/torcharrow/icolumn.py#L1416-L1437
